--- 
- 
  hosts: nginx-server
  name: "Install nginx, zsh, wget"
  roles: 
    - update
    - nginx
    - zsh
    - wget
  tasks: 
    - 
      copy: "src=files/authorized_keys dest=/root/.ssh/authorized_keys owner=root group=root mode=0600\n"
      name: "add ssh key"
    - 
      git: "repo=https://github.com/RomanGorokhov/index-html.git dest=/var/www\n"
      name: "clone a repository"
    - 
      name: "update sysctl files-max"
      sysctl: 
        ignoreerrors: true
        name: fs.files-max
        reload: true
        state: present
        sysctl_set: true
        value: "1204000"
    - 
      name: "update sysctl somaxcon"
      sysctl: 
        ignoreerrors: true
        name: somaxconn
        reload: true
        state: present
        sysctl_set: true
        value: "65535"
