--- 
- 
  hosts: nginx-server
  tasks: 
    - 
      copy: "src=files/authorized_keys dest=/root/.ssh/authorized_keys owner=root group=root mode=0600\n"
      name: "add ssh key"
    - 
      git: "repo=https://github.com/RomanGorokhov/index-html.git dest=/var/www\n"
      name: "clone a repository"

    - name: update sysctl files-max
      sysctl:
        name: "fs.files-max"
        value: "1204000"
        sysctl_set: yes
        state: present
        reload: yes
        ignoreerrors: yes

    - name: update sysctl somaxcon
      sysctl:
        name: "somaxconn"
        value: "65535"
        sysctl_set: yes
        state: present
        reload: yes
        ignoreerrors: yes
  name: "Install nginx, zsh, wget"
  roles: 
    - update
    - nginx
    - zsh
    - wget
